### ISSUE TITLE
刷新过程中，往上滑动，progress 不消失

### ISSUE THREAD

**Issue by philos3** [lovejjfg/PowerRefresh#1]
刷新过程中，recycleview往上滑动，显示的progress 不往上滑液不消失

**Comment by lovejjfg** [comment]
额，这个是个问题，因为原型是 SwipeRefreshLayout  ，之前计划有修改的，结果耽搁了。

**Comment by lovejjfg** [comment]
continue to delay 🤣🤣🤣
