### ISSUE TITLE
Add to update status without calling refresh listener

### ISSUE THREAD

**Issue by abdularis** [lovejjfg/PowerRefresh#3]
This is great, but I think it needs a method where you can set the view to specific state such as refreshing state without calling on refresh listener, it should be maybe to setRefresing() in android SwipeRefreshLayout

**Comment by lovejjfg** [comment]
Maybe the `setAutoRefresh(boolean isAutoRefresh)` method will help you.
https://github.com/lovejjfg/PowerRefresh/blob/2f8972eec02079d0d47b151c2a44813db799a52d/powerrefresh/src/main/java/com/lovejjfg/powerrefresh/PowerRefreshLayout.java#L609
